const journey = [
  ["SUMMER 25", "BD Member", "Built my foundation in outreach, value creation and execution."],
  ["WINTER 25", "TL iGV Raising", "Moved from individual contribution to leading people and managing delivery."],
  ["SUMMER 26", "LCVP B2C · OGT · CXP OGX", "Led product, customer experience and conversion while serving as MC IM staff."],
  ["WINTER 26", "LCVP OGT · CXP OGX", "Turning peak learnings into stronger routines, people development and sustainable performance."],
];

const experiences = [
  {n:"01", title:"National #1 · Global #4", role:"LCVP OGT — Summer 2026", text:"I owned the balance between member experience and product performance, pushed beyond my limits, supported my EB, and translated analysis into execution. The result was first place nationally and fourth globally in OGT approvals.", learn:"Learning: performance becomes sustainable only when strong strategy is matched by intentional investment in people."},
  {n:"02", title:"Learning to Lead", role:"TL iGV Raising — Winter 2025", text:"My first leadership experience exposed me to real-time problem solving, different working styles and the responsibility of creating clarity for others—not only completing my own tasks.", learn:"Learning: leadership is not having every answer; it is creating the environment where people can find and own the answer."},
  {n:"03", title:"Building the Foundation", role:"BD Member — Summer 2025", text:"BD taught me how to communicate value, listen before proposing a solution and keep moving through uncertainty. It shaped the practical mindset I later brought into exchange and customer experience.", learn:"Learning: a strong solution starts with understanding the reality, not assuming it."},
];

const layers = [
  ["CORE", "One national source of truth", "SOPs, Exchange Standards, funnel definitions, role expectations and quality minimums."],
  ["ROLE", "Right depth for each audience", "Separate paths for members, team leaders and LCVPs, with practical cases for each responsibility."],
  ["REALITY", "Adapted to LC maturity", "Foundation track for new/struggling LCs, acceleration track for stable LCs, and advanced optimization for top performers."],
  ["ACTION", "Education that changes behavior", "Every module ends with a task, simulation or funnel action—not passive attendance."],
];

export default function Home() {
  return <main>
    <nav className="nav"><a className="brand" href="#top"><span>GT</span> EDUCATION LAB</a><div><a href="#story">Journey</a><a href="#answers">Application</a><a href="#system">System</a></div></nav>

    <section className="hero" id="top">
      <div className="hero-copy"><p className="eyebrow">EDUCATIONAL MANAGER · OGT EGYPT · EDT 26.2</p><h1>Knowledge should<br/><em>move people.</em></h1><p className="lede">I’m Yassin ElHawash—an OGT leader, cybersecurity engineer and relentless problem-solver. I want to turn national knowledge into clear, competitive and memorable learning experiences that unlock every LC’s potential.</p><div className="hero-actions"><a className="button" href="#answers">Enter the application <b>↘</b></a><span className="status"><i/> Available for impact</span></div></div>
      <div className="portrait-card"><img src="https://raw.githubusercontent.com/Yassin-711/edteduogt/main/public/yassin.jpeg" alt="Yassin ElHawash"/><div className="rank"><small>SUMMER 2026</small><strong>#1 Egypt</strong><span>#4 Global · OGT APDs</span></div></div>
      <div className="ticker"><span>ENTHUSIASTIC</span><span>CLEVER</span><span>CREATIVE</span><span>MODERN</span></div>
    </section>

    <section className="profile panel" id="story"><div><p className="section-no">01 / PROFILE</p><h2>Built in Alexandria.<br/>Designed to <i>innovate.</i></h2></div><div className="facts"><p><b>Current role</b>LCVP OGT & CXP OGX</p><p><b>Local Committee</b>AIESEC in Alexandria</p><p><b>Based in</b>Alexandria, Egypt</p><p><b>Background</b>Cybersecurity Engineer</p><p><b>Email</b><a href="mailto:yassinamr@aiesec.net">yassinamr@aiesec.net</a></p><p><b>WhatsApp</b>+20 120 351 1953</p><p><b>LinkedIn</b><a href="https://www.linkedin.com/in/yassin-amr-330930196/">yassin-amr-330930196</a></p></div></section>

    <section className="journey panel"><div className="heading"><p className="section-no">02 / MY AIESEC JOURNEY</p><h2>One year.<br/><i>Four evolutions.</i></h2><p>I joined in Summer 2025. Each role expanded the way I understand people, products and execution.</p></div><div className="timeline">{journey.map(([date,title,text],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><small>{date}</small><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="manifesto"><p>“You are valuable—and nothing can stop you when knowledge becomes action.”</p><span>MY LEADERSHIP BELIEF</span></section>

    <section className="panel" id="answers"><div className="heading split"><div><p className="section-no">03 / GENERAL QUESTIONS</p><h2>Why this role?<br/><i>Why me?</i></h2></div><p>My application is not only telling you how I educate. It is designed as proof of how learning can feel: structured, visual, engaging and different.</p></div>
      <div className="answer-grid"><article><b>01</b><h3>Why Educational Manager?</h3><p>Education is the base of every achievement. Knowledge gives people the power to understand their purpose and act with confidence. By seeing the realities of different LCs, I can gain a clearer national perspective on Global Talent while helping the commission operate with stronger product knowledge. I believe GT can reach the numerical strength of GV when its people have the clarity, tools and belief to unlock its potential.</p><p>I want to develop my instructional design, facilitation and national network-management skills while introducing digital, gamified and practical ways of learning that OGT membership has not experienced before.</p></article><article><b>02</b><h3>What makes me the right candidate?</h3><p>I combine product ownership with the mindset of an educator and builder. As a current LCVP OGT and CXP OGX, I understand exchange, conversion and the reality behind the numbers. I have led teams, managed customer experience and delivered results under pressure. Ranking first nationally and fourth globally proves that I can translate analysis into execution.</p><p>My cybersecurity background makes me systematic and analytical; my AIESEC journey makes me people-centered. Together, they allow me to structure complex knowledge clearly, diagnose gaps, design modern experiences and keep education connected to performance.</p></article></div>
    </section>

    <section className="experiences panel"><p className="section-no">04 / THREE DEFINING EXPERIENCES</p><h2>Proof over promises.</h2><div className="case-grid">{experiences.map(x=><article key={x.n}><span>{x.n}</span><small>{x.role}</small><h3>{x.title}</h3><p>{x.text}</p><footer>{x.learn}</footer></article>)}</div></section>

    <section className="system panel" id="system"><div className="heading split"><div><p className="section-no">05 / FUNCTIONAL Q1</p><h2>One standard.<br/><i>Different realities.</i></h2></div><p>I would never confuse consistency with uniformity. Every LC needs the same quality standard—but not the same starting point, examples or pace.</p></div><div className="layers">{layers.map(([tag,title,text])=><article key={tag}><span>{tag}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="formula"><b>DIAGNOSE</b><i>→</i><b>SEGMENT</b><i>→</i><b>LEARN</b><i>→</i><b>APPLY</b><i>→</i><b>MEASURE</b></div></section>

    <section className="engage panel"><div className="heading"><p className="section-no">06 / FUNCTIONAL Q2</p><h2>Make education<br/><i>impossible to ignore.</i></h2></div><div className="orbit"><div className="core"><span>THE<br/>LEARNER</span></div>{[["01","MICRO","Short visual modules built around one decision."],["02","PLAY","Scenarios, simulations, challenges and LC battles."],["03","SHOW","Real EP journeys, real objections and real funnel cases."],["04","DO","Templates and missions applied directly after learning."],["05","PROVE","Fast knowledge checks plus observable behavior change."]].map((x,i)=><article className={`o o${i+1}`} key={x[1]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><p className="callout">Clarity comes from hierarchy: one objective, one story, one action. Engagement comes from relevance: members see themselves, their LC and their current problems inside the material.</p></section>

    <section className="tracking panel"><div className="heading split"><div><p className="section-no">07 / FUNCTIONAL Q3</p><h2>Track the cascade.<br/><i>Measure the change.</i></h2></div><p>Tracking is not chasing attendance. It is understanding behavior, creating clear ownership and proving that learning reached local operations.</p></div><div className="dashboard"><div className="metric"><span>1</span><h3>Delivery</h3><p>Named LC education owner, session calendar, attendance evidence and completion deadline.</p></div><div className="metric"><span>2</span><h3>Knowledge</h3><p>Pre/post checks, scenario-based quizzes and certification for critical SOP topics.</p></div><div className="metric"><span>3</span><h3>Application</h3><p>Weekly mission submission, manager observation and sample audits of member execution.</p></div><div className="metric"><span>4</span><h3>Impact</h3><p>Compare funnel conversion, response time and quality indicators before and after education.</p></div></div><div className="tracker-table"><div><b>LC pulse</b><span>Attendance</span><span>Knowledge</span><span>Action</span><span>Conversion</span></div><div><b>Foundation track</b><span>Weekly</span><span>≥80%</span><span>1 mission</span><span>Bi-weekly</span></div><div><b>Acceleration track</b><span>Bi-weekly</span><span>≥85%</span><span>1 experiment</span><span>Weekly</span></div><div><b>Advanced track</b><span>Monthly</span><span>Peer certified</span><span>Case share</span><span>Weekly</span></div></div></section>

    <section className="closing"><p className="section-no">08 / CLOSING</p><h2>Let’s make GT knowledge<br/>a <i>competitive advantage.</i></h2><p>I am applying to build an education system that respects different LC realities, makes complex exchange knowledge simple, and turns every learning touchpoint into measurable action.</p><a className="button light" href="mailto:yassinamr@aiesec.net">Start the conversation ↗</a><footer><span>YASSIN ELHAWASH · OGT EDUCATIONAL MANAGER</span><span>AIESEC IN ALEXANDRIA · 2026</span></footer></section>
  </main>
}
